# Welcome to Jekyll!

# Website settings
title: "Hafiz Muhammad Owais"
description: "Senior System Lead ADAS/HAD Solutions"
keywords: "ADAS, autonomous driving, system architecture, perception systems, automotive, deep learning, computer vision"
baseurl: ""
url: "https://owais2k12.github.io"

# author
author:
  name: 'Owais'
  first_name: 'Hafiz Muhammad'
  last_name: 'Owais'
  email: 'owais.rehman7@yahoo.com'
  linkedin_username: 'https://linkedin.com/in/owais2k12'
  phone: '+49-1573-1140-196'
  location: 'Ingolstadt, Germany'
  head_img: 'static/img/landing/my_pic.JPG'
  desc: "System Lead with 8+ years proven success leading end-to-end development of vehicle functions for ADAS and autonomous driving systems across major automotive brands. Expert in defining and executing function roadmaps, ensuring alignment with global vehicle programs, quality standards (ISO 26262, ASPICE), and production readiness." 
  

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'awards'
    i18n: 'nav.awards'
    name: 'Awards & Honors'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: 'publications'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# analytics (optional)
ga:
  id: '' # Add your Google Analytics ID here if needed

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
